[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-20_x"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan migrate --force",
  "php artisan db:seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"

[variables]
PORT = "8080"
PHP_VERSION = "8.2"
