[build]
builder = "nixpacks"

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.start]
cmds = ["php artisan serve --host=0.0.0.0 --port=$PORT"]

[variables]
PHP_VERSION = "8.2"
